<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Build & Packaging -->
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.103" />

    <!-- Core Dependencies -->
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    <PackageVersion Include="DocumentFormat.OpenXml" Version="3.4.1" />
    <PackageVersion Include="PdfPig" Version="0.1.13" />

    <!-- Testing -->
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="FluentAssertions" Version="8.8.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="coverlet.collector" Version="8.0.0" />

    <!-- Benchmarks -->
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />

    <!-- Samples -->
    <PackageVersion Include="Scalar.AspNetCore" Version="2.12.41" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.3" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>
</Project>
