<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Unio\Unio.csproj" />
    <ProjectReference Include="..\..\src\Unio.Excel\Unio.Excel.csproj" />
    <ProjectReference Include="..\..\src\Unio.Pdf\Unio.Pdf.csproj" />
    <ProjectReference Include="..\..\src\Unio.Json\Unio.Json.csproj" />
    <ProjectReference Include="..\..\src\Unio.Xml\Unio.Xml.csproj" />
    <ProjectReference Include="..\..\src\Unio.Validation\Unio.Validation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
